name: dough
description: This library provides widgets that can be used to create a smooshy user interface.
version: 0.3.7
repository: https://github.com/josiahsrc/flutter_dough
homepage: https://josiahsaunders.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors: ^2.0.0
  equatable: ^2.0.0
  vector_math: ^2.1.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0
